language: ruby
cache: bundler
rvm:
  - 2.3.1
services:
  - postgresql
addons:
  code_climate:
    repo_token: 4dc304037b3711b56720e0037de8973f31060286bef050da39f6df5dd45ef8f3
after_success:
  - bundle exec codeclimate-test-reporter
